import { slugify } from '../components/experiments/experimentFormHelpers';

/**
 * PRD 10 Phase F — "New QEC experiment" templates.
 *
 * Each template scaffolds a QEC memory campaign as REAL, EDITABLE files: a
 * stim-generating Python entry (`nuclei_circuits(noise)`) plus a schema-2
 * `qec_campaign` YAML that points at it. Nothing is hidden behind a built-in
 * generator — the student can open the `.py`, change distances, swap the code
 * task, or hand-build circuits, and the campaign picks it up.
 *
 * The entry circuits are labeled `d=3` / `d=5` / `d=7`; the campaign runner
 * parses that convention (`distanceFromLabel`) so the threshold panel fits Λ
 * across distances exactly as it does for `generate:` sources.
 */

export interface QecTemplateFile {
  /** Path relative to the project root. */
  relPath: string;
  content: string;
  language: 'python' | 'yaml';
}

export interface QecScaffold {
  entryRelPath: string;
  yamlRelPath: string;
  /** The YAML file — the one to select/open after writing. */
  yamlFile: QecTemplateFile;
  files: QecTemplateFile[];
}

export interface QecTemplate {
  id: string;
  label: string;
  description: string;
  build(name: string): QecScaffold;
}

/** Shared header for the generated entry sources. */
function entryHeader(codeTask: string, human: string): string {
  return `"""${human}

Generated by Nuclei's "New QEC experiment" template — a real, editable entry
source. The campaign calls \`nuclei_circuits(noise)\` once per noise grid point;
\`noise\` is the resolved dict for that point ({p, ...stim generator args}).

Edit freely: add distances, change the code task, or build the circuits by
hand. Circuit labels follow the \`d=<n>\` convention so the threshold panel can
fit Lambda across distances.

Code task: ${codeTask}
"""

import stim

# Distances swept for the threshold / Lambda fit. Add or remove as you like.
DISTANCES = (3, 5, 7)
`;
}

/** The identical body both memory templates share (only the code task differs). */
function nucleiCircuitsBody(codeTask: string): string {
  return `
def nuclei_circuits(noise: dict) -> "dict[str, stim.Circuit]":
    p = float(noise.get("p", 1e-3))
    # Generator-expressible models hand us the four channel strengths; fall
    # back to p so the entry still works with a bare {p} dict.
    args = {
        "after_clifford_depolarization": noise.get("after_clifford_depolarization", p),
        "before_round_data_depolarization": noise.get("before_round_data_depolarization", p),
        "before_measure_flip_probability": noise.get("before_measure_flip_probability", p),
        "after_reset_flip_probability": noise.get("after_reset_flip_probability", p),
    }
    circuits: "dict[str, stim.Circuit]" = {}
    for d in DISTANCES:
        circuits[f"d={d}"] = stim.Circuit.generated(
            "${codeTask}",
            rounds=3 * d,
            distance=d,
            **args,
        )
    return circuits
`;
}

/** Build the campaign YAML (hand-written so it keeps teaching comments). */
function campaignYaml(name: string, entryRelPath: string, pRange: [number, number, number]): string {
  return `# QEC memory campaign — edit anything here, or the entry source it points at.
schema: 2
type: qec_campaign
name: ${name}
source:
  # A Python entry file defining nuclei_circuits(noise). Open it to change
  # distances or the code task.
  entry: ${entryRelPath}
noise:
  # A built-in model or a project noise/*.noise.yaml (by its name:).
  model: uniform_depolarizing
  # Physical error rate swept low → high: [start, stop, step].
  p:
    range: [${pRange[0]}, ${pRange[1]}, ${pRange[2]}]
decoders:
  - pymatching
collect:
  # Stop each task at whichever limit comes first.
  max_shots: 100000
  max_errors: 500
workers: auto
`;
}

export const QEC_TEMPLATES: readonly QecTemplate[] = [
  {
    id: 'repetition-memory',
    label: 'Repetition code memory',
    description:
      'The simplest QEC experiment: a d=3/5/7 repetition-code memory swept over physical error rate. A one-dimensional code — ideal for a first threshold/Λ plot.',
    build(name: string): QecScaffold {
      const slug = slugify(name) || 'repetition-memory';
      const entryRelPath = `qec/${slug.replace(/-/g, '_')}.py`;
      const yamlRelPath = `experiments/${slug}.experiment.yaml`;
      const entryFile: QecTemplateFile = {
        relPath: entryRelPath,
        language: 'python',
        content:
          entryHeader('repetition_code:memory', 'Repetition-code memory circuits.') +
          nucleiCircuitsBody('repetition_code:memory'),
      };
      const yamlFile: QecTemplateFile = {
        relPath: yamlRelPath,
        language: 'yaml',
        content: campaignYaml(name, entryRelPath, [0.01, 0.06, 0.01]),
      };
      return { entryRelPath, yamlRelPath, yamlFile, files: [entryFile, yamlFile] };
    },
  },
  {
    id: 'surface-memory',
    label: 'Rotated surface code memory',
    description:
      'A d=3/5/7 rotated surface-code memory (Z basis) swept over physical error rate. The workhorse 2-D code — watch Λ climb as distance grows below threshold.',
    build(name: string): QecScaffold {
      const slug = slugify(name) || 'surface-memory';
      const entryRelPath = `qec/${slug.replace(/-/g, '_')}.py`;
      const yamlRelPath = `experiments/${slug}.experiment.yaml`;
      const entryFile: QecTemplateFile = {
        relPath: entryRelPath,
        language: 'python',
        content:
          entryHeader('surface_code:rotated_memory_z', 'Rotated surface-code memory (Z basis).') +
          nucleiCircuitsBody('surface_code:rotated_memory_z'),
      };
      const yamlFile: QecTemplateFile = {
        relPath: yamlRelPath,
        language: 'yaml',
        content: campaignYaml(name, entryRelPath, [0.001, 0.006, 0.001]),
      };
      return { entryRelPath, yamlRelPath, yamlFile, files: [entryFile, yamlFile] };
    },
  },
];
