import Foundation
import NucleiKit

/// Turns a snapshot into shareable text. Getting a circuit *out* of the phone —
/// into a message, a desktop session, a lab notebook — is a core mobile need, so
/// the share sheet offers real Qiskit you can paste and run.
enum CircuitExport {
    static func qiskit(_ snapshot: CircuitSnapshot) -> String {
        var lines = [
            "# Generated by Nuclei for iOS",
            "from qiskit import QuantumCircuit",
            "",
            "qc = QuantumCircuit(\(snapshot.qubit_count), \(snapshot.classical_bit_count))",
        ]
        for g in snapshot.gates {
            lines.append(qiskitCall(for: g))
        }
        return lines.joined(separator: "\n")
    }

    private static func qiskitCall(for g: Gate) -> String {
        let t = g.targets
        let c = g.controls
        let angle = g.params.first.map { String(format: "%.6f", $0) } ?? "0"
        switch g.type.uppercased() {
        case "H": return "qc.h(\(t[0]))"
        case "X": return "qc.x(\(t[0]))"
        case "Y": return "qc.y(\(t[0]))"
        case "Z": return "qc.z(\(t[0]))"
        case "S": return "qc.s(\(t[0]))"
        case "SDG": return "qc.sdg(\(t[0]))"
        case "T": return "qc.t(\(t[0]))"
        case "TDG": return "qc.tdg(\(t[0]))"
        case "RX": return "qc.rx(\(angle), \(t[0]))"
        case "RY": return "qc.ry(\(angle), \(t[0]))"
        case "RZ": return "qc.rz(\(angle), \(t[0]))"
        case "CNOT", "CX": return "qc.cx(\(c[0]), \(t[0]))"
        case "CZ": return "qc.cz(\(c[0]), \(t[0]))"
        case "SWAP": return "qc.swap(\(t[0]), \(t[1]))"
        case "MEASURE": return "qc.measure(\(t[0]), \(t[0]))"
        default: return "# unsupported: \(g.type)"
        }
    }

    /// A one-line-per-gate human summary for Dirac prompts and quick copy.
    static func summary(_ snapshot: CircuitSnapshot) -> String {
        let gateList = snapshot.gates.map { g -> String in
            let ctrl = g.controls.isEmpty ? "" : "c\(g.controls) "
            let ang = g.params.isEmpty ? "" : String(format: "(%.2fπ)", (g.params[0] / .pi))
            return "\(g.type)\(ang) \(ctrl)q\(g.targets)"
        }.joined(separator: ", ")
        return "\(snapshot.qubit_count) qubits, depth \(snapshot.depth): \(gateList.isEmpty ? "empty" : gateList)"
    }
}
