import { create } from 'zustand';
import { DIRAC_API_KEY } from '../config/dirac';
import {
  buildConversation,
  newConversation,
  readConversation,
  writeConversation,
  type PersistedConversation,
} from '../lib/diracPersistence';

const API_KEY_STORAGE_KEY = 'nuclei-dirac-api-key';

/** Load persisted API key from localStorage, falling back to env config. */
function loadApiKey(): string | null {
  try {
    const stored = localStorage.getItem(API_KEY_STORAGE_KEY);
    if (stored) return stored;
  } catch { /* restricted environment */ }
  return DIRAC_API_KEY || null;
}

/** Persist API key to localStorage. Removes the entry when key is null/empty. */
function persistApiKey(key: string | null): void {
  try {
    if (key) {
      localStorage.setItem(API_KEY_STORAGE_KEY, key);
    } else {
      localStorage.removeItem(API_KEY_STORAGE_KEY);
    }
  } catch { /* restricted environment */ }
}

export interface ToolCall {
  id: string;
  name: string;
  input: Record<string, unknown>;
  status: 'pending' | 'accepted' | 'rejected' | 'executed';
  result?: string;
}

export interface DiracMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string; // ISO-8601; generated at append time
  thinking?: string; // extended thinking content
  toolCalls?: ToolCall[];
}

export interface AmbientMessage {
  id: string;
  kind: 'parse' | 'result';
  text: string;
  timestamp: number;
}

export interface StoredRewrittenError {
  explanation: string;
  fix: string | null;
  originalTraceback: string;
  timestamp: number;
}

export interface ComposePreview {
  id: string;
  intent: string;
  code: string;
  explanation: string;
  timestamp: number;
}

/** Metadata tracked alongside messages so we can round-trip stable IDs
 * to disk. Null until the first message is appended or a conversation is
 * loaded from disk. */
export interface ConversationMeta {
  conversationId: string;
  createdAt: string;
}

/** Payload used by `addMessage` — id and timestamp are generated by the
 * store so callers never think about them. */
type NewMessageInput = Omit<DiracMessage, 'id' | 'timestamp'>;

interface DiracState {
  messages: DiracMessage[];
  conversationMeta: ConversationMeta | null;
  isLoading: boolean;
  apiKey: string | null;
  ambientFeed: AmbientMessage[];
  rewrittenError: StoredRewrittenError | null;
  composePreview: ComposePreview | null;
  addMessage: (msg: NewMessageInput) => void;
  updateLastAssistant: (content: string) => void;
  updateLastThinking: (thinking: string) => void;
  updateLastToolCalls: (toolCalls: ToolCall[]) => void;
  updateToolCallStatus: (toolId: string, status: ToolCall['status'], result?: string) => void;
  setLoading: (loading: boolean) => void;
  setApiKey: (key: string | null) => void;
  clearHistory: () => void;
  /** Replace in-memory conversation with a loaded-from-disk one.
   * Used by the project-open and app-start restore paths. */
  loadConversation: (conversation: PersistedConversation) => void;
  /** Clear in-memory conversation WITHOUT triggering a write. Used when
   * switching projects — the incoming project's file is loaded next. */
  resetConversation: () => void;
  pushAmbient: (msg: Omit<AmbientMessage, 'id' | 'timestamp'>) => void;
  clearAmbient: () => void;
  setRewrittenError: (err: Omit<StoredRewrittenError, 'timestamp'>) => void;
  clearRewrittenError: () => void;
  setComposePreview: (p: Omit<ComposePreview, 'id' | 'timestamp'>) => void;
  clearComposePreview: () => void;
}

function nowIso(): string {
  return new Date().toISOString();
}

function ensureMeta(meta: ConversationMeta | null): ConversationMeta {
  if (meta) return meta;
  const fresh = newConversation();
  return { conversationId: fresh.conversation_id, createdAt: fresh.created_at };
}

function hydrateMessage(input: NewMessageInput): DiracMessage {
  return {
    id: crypto.randomUUID(),
    timestamp: nowIso(),
    ...input,
  };
}

export const useDiracStore = create<DiracState>((set) => ({
  messages: [],
  conversationMeta: null,
  isLoading: false,
  apiKey: loadApiKey(),
  ambientFeed: [],
  rewrittenError: null,
  composePreview: null,
  addMessage: (msg) => set((s) => ({
    messages: [...s.messages, hydrateMessage(msg)],
    // Lazily create metadata on first message so a fresh session gets a
    // stable conversation_id to persist. Existing meta (e.g. from a
    // loadConversation) is preserved.
    conversationMeta: ensureMeta(s.conversationMeta),
  })),
  updateLastAssistant: (content) => set((s) => {
    const msgs = [...s.messages];
    const lastIdx = msgs.length - 1;
    if (lastIdx >= 0 && msgs[lastIdx].role === 'assistant') {
      msgs[lastIdx] = { ...msgs[lastIdx], content };
    }
    return { messages: msgs };
  }),
  updateLastThinking: (thinking) => set((s) => {
    const msgs = [...s.messages];
    const lastIdx = msgs.length - 1;
    if (lastIdx >= 0 && msgs[lastIdx].role === 'assistant') {
      msgs[lastIdx] = { ...msgs[lastIdx], thinking };
    }
    return { messages: msgs };
  }),
  updateLastToolCalls: (toolCalls) => set((s) => {
    const msgs = [...s.messages];
    const lastIdx = msgs.length - 1;
    if (lastIdx >= 0 && msgs[lastIdx].role === 'assistant') {
      msgs[lastIdx] = { ...msgs[lastIdx], toolCalls };
    }
    return { messages: msgs };
  }),
  updateToolCallStatus: (toolId, status, result) => set((s) => {
    const msgs = s.messages.map((m) => {
      if (!m.toolCalls) return m;
      const updated = m.toolCalls.map((tc) =>
        tc.id === toolId ? { ...tc, status, result: result ?? tc.result } : tc
      );
      return { ...m, toolCalls: updated };
    });
    return { messages: msgs };
  }),
  setLoading: (isLoading) => set({ isLoading }),
  setApiKey: (apiKey) => {
    persistApiKey(apiKey);
    set({ apiKey });
  },
  // Keep the conversationId stable on clear so the persisted file stays
  // in place for the future "multiple conversations per project" migration.
  // The subscription below writes `messages: []` to disk when this runs.
  clearHistory: () => set((s) => ({
    messages: [],
    conversationMeta: ensureMeta(s.conversationMeta),
  })),
  loadConversation: (conversation) => set({
    messages: conversation.messages,
    conversationMeta: {
      conversationId: conversation.conversation_id,
      createdAt: conversation.created_at,
    },
  }),
  resetConversation: () => set({ messages: [], conversationMeta: null }),
  pushAmbient: (msg) => set((s) => ({
    ambientFeed: [
      ...s.ambientFeed.slice(-4), // cap at last 5 including the new entry
      { ...msg, id: crypto.randomUUID(), timestamp: Date.now() },
    ],
  })),
  clearAmbient: () => set({ ambientFeed: [] }),
  setRewrittenError: (err) => set({ rewrittenError: { ...err, timestamp: Date.now() } }),
  clearRewrittenError: () => set({ rewrittenError: null }),
  setComposePreview: (p) => set({
    composePreview: { ...p, id: crypto.randomUUID(), timestamp: Date.now() },
  }),
  clearComposePreview: () => set({ composePreview: null }),
}));

// ───────────────────────── auto-save ─────────────────────────
//
// Every time `messages` changes we persist the conversation to
// <projectRoot>/.nuclei/dirac.json (desktop w/ project), app-store
// (desktop no project), or localStorage (web). Writes are debounced 300ms
// so a streaming assistant response doesn't pound the disk, and only one
// write is ever in flight at a time — a later change received while a
// write is running coalesces into a single follow-up.

const DEBOUNCE_MS = 300;
// Set by the projectStore integration so we don't import projectStore here
// (avoiding a circular dep: diracStore → diracPersistence → platform,
//  projectStore → diracStore). The getter returns null when no project
// is open, which routes writes to the ephemeral path.
let projectRootGetter: () => string | null = () => null;
export function __setProjectRootGetter(getter: () => string | null): void {
  projectRootGetter = getter;
}

let pendingTimer: ReturnType<typeof setTimeout> | null = null;
let writeInFlight = false;
let rewriteQueued = false;

async function runPersist(): Promise<void> {
  if (writeInFlight) {
    // Caller arrived while a write is running — coalesce into a single
    // follow-up that fires as soon as the current one finishes. Returning
    // here instead of awaiting a second pass keeps re-entrant callers
    // from piling up futures that all resolve on the same final write.
    rewriteQueued = true;
    return;
  }
  writeInFlight = true;
  try {
    const state = useDiracStore.getState();
    const meta = state.conversationMeta;
    // No meta = nothing to persist yet (no messages and no loaded conversation).
    if (!meta) return;
    const conversation = buildConversation(state.messages, meta);
    await writeConversation(projectRootGetter(), conversation);
  } finally {
    writeInFlight = false;
    const shouldRewrite = rewriteQueued;
    rewriteQueued = false;
    if (shouldRewrite) {
      // Await the follow-up so callers (flush hooks, tests) know when the
      // full cascade has drained. No debounce — starving a rapid tail of
      // edits would leave the final state unwritten.
      await runPersist();
    }
  }
}

function schedulePersist(): void {
  if (writeInFlight) {
    // Change arrived during a live write — flag it for the in-flight
    // pass to pick up in its finally block. Skip the debounce timer
    // entirely so streaming responses don't queue a dozen deferred writes.
    rewriteQueued = true;
    return;
  }
  if (pendingTimer) clearTimeout(pendingTimer);
  pendingTimer = setTimeout(() => {
    pendingTimer = null;
    void runPersist();
  }, DEBOUNCE_MS);
}

// Flush timers synchronously — for tests and potential app-shutdown hooks.
export async function __flushPersistenceForTests(): Promise<void> {
  if (pendingTimer) {
    clearTimeout(pendingTimer);
    pendingTimer = null;
  }
  await runPersist();
}

useDiracStore.subscribe((state, prev) => {
  if (state.messages !== prev.messages) {
    schedulePersist();
  }
});

// ───────────────────────── restore ─────────────────────────

/**
 * Load the conversation persisted for a project, replacing in-memory
 * state. Call on project open; call with `null` on app start when no
 * project is open (loads ephemeral). Caller is responsible for deciding
 * whether to load ephemeral vs stay empty — this helper just reads and
 * applies whatever exists.
 */
export async function loadDiracConversationForProject(
  projectRoot: string | null,
): Promise<void> {
  const conversation = await readConversation(projectRoot);
  if (conversation) {
    useDiracStore.getState().loadConversation(conversation);
    if (conversation.messages.length > 0) {
      console.info(
        `[Dirac] restored ${conversation.messages.length} messages from ` +
          (projectRoot ? `${projectRoot}/.nuclei/dirac.json` : 'ephemeral store') +
          `; last update ${conversation.updated_at}`,
      );
    }
  } else {
    // Fresh start — drop any in-memory state so we don't leak chat from
    // a previous project into the new one.
    useDiracStore.getState().resetConversation();
  }
}
